theme: jekyll-theme-minimal
title: Ziqi Huang
description: PhD student at McGill University


# This helps the theme identify your social profiles
linkedin_username: ziqi-huang-334b88201
github_username: ZiqiHuang11
